# Generated by Django 3.0.8 on 2020-07-13 18:55

import crm.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, unique=True, verbose_name='Pais')),
                ('cod_coin', models.CharField(max_length=3, verbose_name='Codigo divisa')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Info_country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.TextField(blank=True, max_length=250, verbose_name='Comida tipica')),
                ('monuments', models.TextField(blank=True, max_length=250, verbose_name='Momumentos')),
                ('museum', models.TextField(blank=True, max_length=250, verbose_name='Museos')),
                ('citys', models.TextField(blank=True, max_length=250, verbose_name='Museos')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_country', to='crm.Country')),
            ],
            options={
                'verbose_name': 'Informacion',
                'verbose_name_plural': 'Informaciones',
            },
        ),
        migrations.CreateModel(
            name='CambioEuro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell', models.FloatField(max_length=12, verbose_name='Venta')),
                ('buy', models.FloatField(max_length=12, verbose_name='Compra')),
                ('cod_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_euro', to='crm.Country')),
            ],
            options={
                'verbose_name': 'Cambio Euro',
                'verbose_name_plural': 'Cambio Euro',
            },
        ),
        migrations.CreateModel(
            name='CambioDolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell', models.FloatField(max_length=12, verbose_name='Venta')),
                ('buy', models.FloatField(max_length=12, verbose_name='Compra')),
                ('cod_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_dolar', to='crm.Country')),
            ],
            options={
                'verbose_name': 'Cambio dolar',
                'verbose_name_plural': 'Cambio dolar',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Nombre')),
                ('nickname', models.CharField(blank=True, max_length=30, verbose_name='Apodo')),
                ('data_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fkuser', to='crm.Country')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', crm.managers.UserManager()),
            ],
        ),
    ]
