# Generated by Django 3.0.8 on 2020-07-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, unique=True, verbose_name='Pais')),
                ('cod_coin', models.CharField(max_length=3, verbose_name='Codigo divisa')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Nombre')),
                ('nickname', models.CharField(blank=True, max_length=30, verbose_name='Apodo')),
                ('data_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.country')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='info_country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.TextField(blank=True, max_length=250, verbose_name='Comida tipica')),
                ('monuments', models.TextField(blank=True, max_length=250, verbose_name='Momumentos')),
                ('museum', models.TextField(blank=True, max_length=250, verbose_name='Museos')),
                ('citys', models.TextField(blank=True, max_length=250, verbose_name='Museos')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.country')),
            ],
            options={
                'verbose_name': 'Informacion',
                'verbose_name_plural': 'Informaciones',
            },
        ),
        migrations.CreateModel(
            name='cambioUsd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell', models.FloatField(max_length=12, verbose_name='Venta')),
                ('buy', models.FloatField(max_length=12, verbose_name='Compra')),
                ('cod_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.country')),
            ],
            options={
                'verbose_name': 'Cambio dolar',
                'verbose_name_plural': 'Cambio dolar',
            },
        ),
        migrations.CreateModel(
            name='cambioEur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell', models.FloatField(max_length=12, verbose_name='Venta')),
                ('buy', models.FloatField(max_length=12, verbose_name='Compra')),
                ('cod_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.country')),
            ],
            options={
                'verbose_name': 'Cambio Euro',
                'verbose_name_plural': 'Cambio Euro',
            },
        ),
    ]
